# Generated by Django 4.2.5 on 2023-12-06 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="firstname",
            new_name="username",
        ),
    ]
