# Generated by Django 4.2.5 on 2023-12-06 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_rename_firstname_user_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="AppUser",
        ),
    ]
