# Generated by Django 4.2.5 on 2023-12-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_rename_user_appuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="first_name",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="appuser",
            name="last_name",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(default="", max_length=150, unique=True),
        ),
    ]
