# Generated by Django 4.2.5 on 2023-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_alter_appuser_options_alter_appuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
