# Generated by Django 4.2.5 on 2023-12-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binsstats",
            name="Lat",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="binsstats",
            name="Lon",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="binsstats",
            name="fillUp",
            field=models.IntegerField(blank=True),
        ),
    ]
