# Generated by Django 4.2.5 on 2023-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_alter_binsstats_lat_alter_binsstats_lon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binsstats",
            name="Lat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="binsstats",
            name="Lon",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
