# Generated by Django 4.2.5 on 2023-12-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0010_alter_binsstats_lat_alter_binsstats_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="binsstats",
            name="City",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="binsstats",
            name="Lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="binsstats",
            name="Lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
