# Generated by Django 4.2.5 on 2023-12-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0012_alter_binsstats_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BINQRs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="qrcode")),
            ],
        ),
    ]
