# Generated by Django 4.2.5 on 2023-12-09 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0013_binqrs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="binqrs",
            old_name="data",
            new_name="url",
        ),
    ]
