# Generated by Django 4.2.5 on 2023-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0014_rename_data_binqrs_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="binqrs",
            name="data",
            field=models.CharField(default="a", max_length=50),
        ),
    ]
