# Generated by Django 4.2.5 on 2023-12-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0016_alter_binqrs_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binqrs",
            name="data",
            field=models.CharField(default="", max_length=50),
        ),
    ]
