# Generated by Django 4.2.5 on 2023-12-09 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0018_alter_binqrs_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="binqrs",
            name="url",
        ),
    ]
